import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import { AuthSync } from "@/components/auth-sync";
import { ConvexClientProvider } from "@/components/convex-client-provider";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <ClerkProvider>
        <ConvexClientProvider>
        <Header />
        {/* <AuthSync /> */}
        <main className="min-h-screen">
          {children}
          <Toaster richColors />
          </main>
        </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
